
CREATE OR REPLACE VIEW VW_BI_RECEBIMENTOS
BEQUEATH DEFINER AS
SELECT NULL DATA_COMPETENCIA,
       NULL /*B.DATA_RECEBIMENTO*/ AS  DATA_PAGAMENTO,
       C."clinica_id" ID_UNIDADE,
       E.CLASSIFICACAO_FINANCEIRA CATEGORIA,
       F."procedimento_id" ID_PROCEDIMENTO,
       C."data" DATA_EXECUCAO,
       B.VALOR AS VALOR_PAGO,
       C."paciente_id" ID_PACIENTE,
       C."profissional_id" ID_PROFISSIONAL,
       C."precificacao_id" ID_CONVENIO,
       D.ITEM_DESCRICAO DESCRICAO_MOVIMENTACAO,
       NULL /*A.FK_FUNCIONARIOS*/ AS ID_FUNCIONARIO,
       /*CASE
          WHEN B.STATUS = 'N' THEN 'Não Quitada'
          WHEN B.STATUS = 'Q' THEN 'Quitada'
          WHEN B.STATUS = 'C' THEN 'Cancelada'
       END*/ NULL STATUS,
       F."tabela_precos_id" AS TABELA_PARCERIA_ID
FROM   RECEBIMENTOS A
INNER  JOIN RECEBIMENTOS_PARCELAS B ON B.FK_RECEBIMENTO = A.ID AND B.FLG_ATIVO = 1 --SELECT * FROM RECEBIMENTOS_PARCELAS
LEFT   OUTER JOIN AGENDAMENTOS C ON C."id" = A.ORIGEM_ID AND A.ORIGEM = 'A'
INNER  JOIN RECEBIMENTOS_ITENS D ON D.FK_RECEBIMENTO = A.ID AND D.FLG_ATIVO = 1
INNER  JOIN CLASSIFICACAO_FINANCEIRA E ON E.ID = D.FK_CLASSIFICACAO_FINANCEIRA AND E.FLG_ATIVO = 1
LEFT   OUTER JOIN AGENDAMENTOS_PROCEDIMENTOS F ON F."agendamento_id" = C."id"
WHERE  A.FLG_ATIVO = 1
GO


/*---ORIGINAL

CREATE OR REPLACE VIEW AMEI_APP_PROD.VW_BI_RECEBIMENTOS ( DATA_COMPETENCIA, DATA_PAGAMENTO, ID_UNIDADE, CATEGORIA, ID_PROCEDIMENTO, DATA_EXECUCAO, VALOR_PAGO, ID_PACIENTE, ID_PROFISSIONAL, ID_CONVENIO, DESCRICAO_MOVIMENTACAO, ID_FUNCIONARIO, STATUS )
BEQUEATH DEFINER AS
SELECT NULL DATA_COMPETENCIA,
       NULL /*B.DATA_RECEBIMENTO*/ AS  DATA_PAGAMENTO,
       C."clinica_id" ID_UNIDADE,
       E.CLASSIFICACAO_FINANCEIRA CATEGORIA,
       F."procedimento_id" ID_PROCEDIMENTO,
       C."data" DATA_EXECUCAO,
       B.VALOR AS VALOR_PAGO,
       C."paciente_id" ID_PACIENTE,
       C."profissional_id" ID_PROFISSIONAL,
       C."precificacao_id" ID_CONVENIO,
       D.ITEM_DESCRICAO DESCRICAO_MOVIMENTACAO,
       NULL /*A.FK_FUNCIONARIOS*/ AS ID_FUNCIONARIO,
       /*CASE
          WHEN B.STATUS = 'N' THEN 'Não Quitada'
          WHEN B.STATUS = 'Q' THEN 'Quitada'
          WHEN B.STATUS = 'C' THEN 'Cancelada'
       END*/ NULL STATUS 
FROM   RECEBIMENTOS A
INNER  JOIN RECEBIMENTOS_PARCELAS B ON B.FK_RECEBIMENTO = A.ID AND B.FLG_ATIVO = 1 --SELECT * FROM RECEBIMENTOS_PARCELAS
LEFT   OUTER JOIN AGENDAMENTOS C ON C."id" = A.ORIGEM_ID AND A.ORIGEM = 'A'
INNER  JOIN RECEBIMENTOS_ITENS D ON D.FK_RECEBIMENTO = A.ID AND D.FLG_ATIVO = 1
INNER  JOIN CLASSIFICACAO_FINANCEIRA E ON E.ID = D.FK_CLASSIFICACAO_FINANCEIRA AND E.FLG_ATIVO = 1
LEFT   OUTER JOIN AGENDAMENTOS_PROCEDIMENTOS F ON F."agendamento_id" = C."id"
WHERE  A.FLG_ATIVO = 1
GO
*/