SELECT * FROM VW_BI_EXAMES_PRONTUARIOS WHERE QUANTIDADE>1 AND ROWNUM <100
SELECT QUANTIDADE FROM VW_BI_EXAMES_PRONTUARIOS

SELECT P.NOME_PROCEDIMENTO, E.* 
FROM VW_BI_EXAMES_PRONTUARIOS E
INNER JOIN VW_BI_PROCEDIMENTOS P ON E.ID_PROCEDIMENTO = P.ID




CREATE OR REPLACE VIEW VW_BI_EXAMES_PRONTUARIOS
BEQUEATH DEFINER AS
SELECT C.ID,
       A."id" ID_AGENDAMENTO,
       B.DATA_ATENDIMENTO DATA,
       A."clinica_id" ID_UNIDADE,
       A."paciente_id" ID_PACIENTE,
       A."profissional_id" ID_PROFISSIONAL,
       A."convenio_id" ID_CONVENIO,
       D.FK_PROCEDIMENTO ID_PROCEDIMENTO,
       COUNT(E."id") AS QUANTIDADE
FROM   AGENDAMENTOS A
INNER  JOIN ATENDIMENTOS B ON B.FK_AGENDAMENTO = A."id" AND B.FLG_ATIVO = 1
INNER  JOIN ATENDIMENTO_EXAMES C ON C.FK_ATENDIMENTO = B.ID AND C.FLG_ATIVO = 1
LEFT   OUTER JOIN ATEND_EXAME_PROCEDIMENTOS D ON D.FK_ATENDIMENTO_EXAME = C.ID AND D.FLG_ATIVO = 1
LEFT   OUTER JOIN AGENDAMENTOS_PROCEDIMENTOS E ON E."agendamento_id" = A."id"
GROUP BY  
       C.ID,
       A."id",
       B.DATA_ATENDIMENTO,
       A."clinica_id",
       A."paciente_id",
       A."profissional_id",
       A."convenio_id",
       D.FK_PROCEDIMENTO
GO


/*----ORIGINAL
CREATE OR REPLACE VIEW AMEI_APP_PROD.VW_BI_EXAMES_PRONTUARIOS ( ID, ID_AGENDAMENTO, DATA, ID_UNIDADE, ID_PACIENTE, ID_PROFISSIONAL, ID_CONVENIO, ID_PROCEDIMENTO )
BEQUEATH DEFINER AS
SELECT C.ID,
       A."id" ID_AGENDAMENTO,
       B.DATA_ATENDIMENTO DATA,
       A."clinica_id" ID_UNIDADE,
       A."paciente_id" ID_PACIENTE,
       A."profissional_id" ID_PROFISSIONAL,
       A."convenio_id" ID_CONVENIO,
       E."procedimento_id" ID_PROCEDIMENTO
FROM   AGENDAMENTOS A
INNER  JOIN ATENDIMENTOS B ON B.FK_AGENDAMENTO = A."id" AND B.FLG_ATIVO = 1
INNER  JOIN ATENDIMENTO_EXAMES C ON C.FK_ATENDIMENTO = B.ID AND C.FLG_ATIVO = 1
LEFT   OUTER JOIN ATEND_EXAME_PROCEDIMENTOS D ON D.FK_ATENDIMENTO_EXAME = C.ID AND D.FLG_ATIVO = 1
LEFT   OUTER JOIN AGENDAMENTOS_PROCEDIMENTOS E ON E."agendamento_id" = A."id"
GROUP BY  C.ID,
       A."id",
       B.DATA_ATENDIMENTO,
       A."clinica_id",
       A."paciente_id",
       A."profissional_id",
       A."convenio_id",
       E."procedimento_id"
GO
*/